name: Reset Discord Permissions

on:
  workflow_dispatch: # Allows manual trigger

jobs:
  reset-permissions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Ensure you're using at least version 16

      - name: Install dependencies
        run: npm install

      - name: Run reset permissions script
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_GUILD_ID: ${{ secrets.DISCORD_GUILD_ID }}
        run: node index.js
